name: Java Maven CI Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Compile Project
        run: mvn clean compile
      - name: Run Test
        run: mvn test
      - name: Package Application
        run: mvn package
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*
      - name: Compile java program
        run: javac src/main/java/App.java
      - name: Run java Program
        run: java -cp src/main/java App